version: '3.9'

services:
  frontend:
    container_name: frontend
    image: seaweedbrain/zero-totp-frontend:latest
    ports: 
      - ${FRONTEND_PORT}
    env_file:
      - .env
    networks:
      - internal
    restart: always

  api:
    container_name: api
    image: seaweedbrain/zero-totp-api:latest
    ports:
      - ${API_PORT}
    env_file:
      - .env
    volumes:
      - ./secret:/api/secret
    restart: always
    networks:
      - internal

networks:
  internal:
    name: "internal_net"