version: '3.9'

services:
  frontend:
    container_name: frontend
    image: seaweedbrain/zero-totp-frontend:latest
    ports: 
      - "127.0.0.1:4200:80"
    env_file:
      - .env

  api:
    container_name: api
    image: seaweedbrain/zero-totp-api:latest
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - .env
  
  database:
    env_file:
      - .env
    image: mysql:latest
    container_name: database
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./database/dbdata:/var/lib/mysql
