
openapi: 3.0.3
info:
  title: zero-totp API
  description: API for the zero-totp application
  version: "1.0"
servers:
  - url: http://127.0.0.1:8080
    description: local API server
security:
  - JWTAuth: []
paths:
  /signup:
    post:
      operationId: controllers.signup
      tags:
        - User
      summary: Sign a user up to the application
      security: []
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                username:
                  type: string
                password:
                  type: string
                ZKE_key:
                  type: string
                  description: The user's ZKE key ENCRYPTED by the user
      responses:
        "201": # status code
          description: Sign up successful
        "400":
          description: Missing required parameters
        "409":
          description: User already exists
  /login:
    post:
      operationId: controllers.login
      tags:
        - User
      summary: Log a user in the application
      security: []
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200": # status code
          description: successful login. The JWT is returned in the response body
        "400":
          description: Missing required parameters
        "403":
          description: Authentication failed
  /vault:
    get:
      operationId: controllers.getVault
      tags:
        - Vault
      summary: Get the user's vault
      responses:
        "200": # status code
          description: Return the user's vault
        "400":
          description: Missing required parameters
        "401":
          description: Unauthorized
        "403":
          description: Access denied

components:
  securitySchemes:
    JWTAuth:
      type: apiKey
      in: cookie
      name: api-key
      x-apikeyInfoFunc: Crypto.jwt_func.verify_jwt

