
openapi: 3.0.3
info:
  title: zero-totp API
  description: API for the zero-totp application
  version: "1.0"
servers:
  - url: http://127.0.0.1:8080
    description: local API server
paths:
  /vault:
    post:
      operationId: controllers.signup
      tags:
        - User
      summary: Sign a user up to the application
      parameters:
        - name: email
          in: query
          description: The email of the user
          required: true
          schema:
            type: string
        - name : username
          in: query
          description: The username of the user
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: The password of the user
          required: true
          schema:
            type: string
      responses:
        "201": # status code
          description: Sign up successful
        "400":
          description: Missing required parameters
        "409":
          description: User already exists
        