name: "Beta deployment"

on:
  push:
    branches:
      - 'main'
jobs:
  - uses: actions/checkout@v3
      docker-frontend:
      name: Publish frontend image
      runs-on: ubuntu-latest
      env:
        REPO: ${{secrets.DOCKER_REPO}}
      steps:
        - name: Login to Docker Hub
          run : docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
        - name: Build Docker image
          working-directory: ./frontend
          run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
        - name: Publish Docker Image
          run: docker push $REPO
