name: "zero-totp.com deployment"

on:
  push:
    tags:
      - '**'

jobs:
    tests_and_security:
      uses: ./.github/workflows/security_analysis.yml  # use the callable tests job to run tests
      secrets:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    docker-frontend:
      needs: [tests_and_security]
      name: Publish Frontend Docker image
      runs-on: ubuntu-latest
      env:
        REPO: ${{secrets.DOCKER_FRONTEND_REPO}}
      steps:
        - uses: actions/checkout@v3
        - name: Login to Docker Hub
          run : docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
        - name: Create environment file
          working-directory: ./frontend
          run: bash generate-env.sh '${{ github.ref_name }}' '${{secrets.RSA_PUBLIC_KEY}}'
        - name: Build Docker image
          working-directory: ./frontend
          run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
        - name: Publish Docker Image
          run: docker push $REPO
    docker-api:
      needs: [tests_and_security]
      name: Publish API Docker image
      runs-on: ubuntu-latest
      env:
        REPO: ${{secrets.DOCKER_API_REPO}}
      steps:
        - uses: actions/checkout@v3
        - name: Login to Docker Hub
          run : docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
        - name: Build Docker image
          working-directory: ./api
          run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
        - name: Publish Docker Image
          run: docker push $REPO
    deploy-production:
       needs: [docker-frontend, docker-api] 
       name: Deploy on production server
       runs-on: ubuntu-latest
       steps:
         - name: Deployment
           uses: distributhor/workflow-webhook@v3
           env:
             webhook_url: ${{ secrets.WEBHOOK_URL }}

        
