name: "Test and Coverage"

on: 
  push:
    branches:
      - '*'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '*'
  workflow_call:
    
  
  

jobs:
  python_test_and_coverage:
    name: Python Test and Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      working-directory: ./api
      run: pip install -r requirements.txt && pip install -r test-requirements.txt

    - name: Run tests with pytest
      working-directory: ./api
      env:
        DATABASE_URI: "sqlite:///:memory:"
        JWT_SECRET : "secret"
<<<<<<< HEAD
<<<<<<< HEAD
        PRIVATE_KEY_PATH: "./tests/ressources/test_private.pem"
        PUBLIC_KEY_PATH: "./tests/ressources/test_public.pem"
=======
        OAUTH_CLIENT_SECRET_FILE: "fake_client_secret.json"
        FLASK_SECRET_KEY: "secret"
>>>>>>> 7d47be5 (Fix actions with new env variables)
=======
        OAUTH_CLIENT_SECRET_FILE: "fake_client_secret.json"
        FLASK_SECRET_KEY: "secret"
>>>>>>> 78f553f023155a4bfb6c29e2a781091694a9dc0f
      run: python -m pytest --cov=. --cov-report=lcov --cov-report=term

    - name: Upload coverage report
      uses: coverallsapp/github-action@v2
        

