name: "Test and Coverage"

on: 
  push:
    branches:
      - '*'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '*'
  workflow_call:
    
  
  

jobs:
  security_scan_analysis:
    name: Security Scan Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    
    - name: Install semgrep
      run: python3 -m pip install semgrep
    
    - name: Run semgrep
      run: semgrep --config=auto

  python_test_and_coverage:
    name: Units test and SonarQube scan
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      working-directory: ./api
      run: pip install -r requirements.txt && pip install -r test-requirements.txt

    - name: Run tests with pytest
      env:
        DATABASE_URI: "sqlite:///:memory:"
        JWT_SECRET : "secret"
        PRIVATE_KEY_PATH: "./api/tests/ressources/test_private.pem"
        PUBLIC_KEY_PATH: "./api/tests/ressources/test_public.pem"
      run: python -m pytest --cov=./api --cov-report=lcov --cov-report=term --cov-report=xml api/
    - name: Upload coverage report
      uses: coverallsapp/github-action@v2
    - name : Debug
      run: pwd && ls -la && ls -la api && cat sonar-project.properties && cat api/coverage.xml
    - name: Sonar scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    #- name: SonarQube Quality Gate check
    #  id: sonarqube-quality-gate-check
    #  uses: sonarsource/sonarqube-quality-gate-action@master
    #  timeout-minutes: 5
    #  env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} #OPTIONAL
  
    #- name: "Example show SonarQube Quality Gate Status value"
    #  run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}" && pwd && cat# sonar-project.properties && ls -la && ls -la api
        

